### ISSUE TITLE
Meta issue: Bare minimum stuff

### ISSUE THREAD

**Issue by anxiousmodernman** [jeffmay/rust_membership_api#3]
i_don't_know_what_im_doing.gif

- [x] demonstrate querying in handlers
- [ ] document adding types that map to tables
- [ ] Integration tests that rebuild, populate, and run against postgres

We will probably end up squashing our db migrations into one big initial schema with a decent set of functionality. We don't need all that trial and error to live on for all time.

**Comment by anxiousmodernman** [comment]
Integration test: https://github.com/jeffmay/rust_membership_api/blob/db_compose/tests/web/app.rs#L24

Doing inserts. Note `Json` gives us our own type at field struct field `0` https://github.com/jeffmay/rust_membership_api/blob/db_compose/src/web/members.rs#L27-L29
